# Generated by Django 5.1.4 on 2025-05-29 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_clue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='clue',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clue',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clue',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='game_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='round_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='word_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='guess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guess',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='clue',
            unique_together={('player', 'game', 'round_number')},
        ),
    ]
